# Time after which to give up on waiting for a mod to download.
request-timeout-millis: 30000

# The directory where all the mods will be downloaded to.
output-dir: ./mods

# Downloads versions of the mods for these loaders.
# Only one file per mod is downloaded.
# There is probably only use-case where you would want to put more loaders and that is in Quilt-Fabric scenario.
loaders: [fabric, quilt]

# List of Minecraft version you want to download the mod for.
# The versions are in order of priority.
# If a mod doesn't have any version for the first mc version, the second will be downloaded.
# If there is no version for the second mc version it will look for the third and so on.
# Mostly useful for mods, whose 1.19 version works for both 1.19 and 1.19.1
# That's how libraries often work.
mc-versions: [1.19.1, 1.19]

# The ids/slugs of the mods you want to download.
# The slug can be found in the URL of the mod.
# Example https://modrinth.com/mod/sodium, slug is sodium.
mods:
  - reeses-sodium-options
  - command-block-ide
  - organized-tabs
  - pick-up-notifier
  - shulkerboxtooltip
  - easiervillagertrading
  - petowner
  - ost-overhaul
  - clickthrough
  - alltheunobtainables
  - roughly-enough-items
  - blockmeter
  - simple-discord-rpc
  - visible-barriers
  - resounding
  - entityculling
  - paperdoll
  - wavey-capes
  - 3dskinlayers
  - moreculling
  - capes
  - indium
  - morechathistory
  - sodium-crash-fix
  - amecs
  - kappa
  - sort
  - jsmacros
  - too-many-binds
  - microdurability
  - map-compass
  - chatcalc
  - vtdownloader
  - screenshot-to-clipboard
  - lambdabettergrass
  - clock-hud
  - nbt-editor
  - betterf3
  - purpurclient
  - boosted-brightness
  - stepup
  - technomodel
  - multiple-server-lists
  - low-fire
  - blur-fabric
  - symbol-chat
  - moderate-loading-screen
  - enhanced-searchability
  - better-end-sky
  - fvt
  - fallingleaves
  - freecam
  - condensed-creative
  - draggable-resource-packs
  - ok-zoomer
  - norefreshscroll
  - forcecloseworldloadingscreen
  - blanket
  - detail-armor-bar
  - cms
  - better-beds
  - modmenu
  - hatlist
  - spectater
  - cit-resewn
  - visuality
  - presence-footsteps
  - worldtime
  - lambdynamiclights
  - fastanim
  - camera-utils
  - continuity
  - sodium
  - item-model-fix
  - sodium-extra
  - invmove
  - dripsounds-fabric
  - iris
  - dynamiccrosshair
  - quickconnectbutton
  - waxednotwaxed
  - perspektive
  - distanthorizons
  - gamma-utils
  - wthit
  - memoryleakfix
  - smoothboot-fabric
  - discerning-furnace
  - suggestion-tweaker
  - visual-overhaul
  - lazydfu
  - ferrite-core
  - vmp-fabric
  - notenoughcrashes
  - starlight
  - debugify
  - krypton
  - lithium

# Not on Modrinth

# Quilt Fabric API
# Command Macros
# Advanced X-Ray
# Controlling
# Item Scroller and MaliLib
# Smooth Scrolling Everywhere
# Toro health indicator
# World Edit CUI
# Xaeros minimap
# Better Third Person

# Not working

# AdvancedChat
# MultiConnect
# All the unobtainables (requires Java 18)